ember-config {
    host = 0.0.0.0
    port = 4041
}

postgres-config {
    n-threads = 32
    url = "jdbc:postgresql://localhost:5436/board"
    user = "docker"
    pass = "docker"
}

security-config {
    secret = "secret"
    jwt-expiry-duration = "1 day"
}

email-service-config {
    host = "smtp.ethereal.email"
    port = 587
    user = "edwin.moen37@ethereal.email"
    pass = "7d6eKuRbD9tFzVqy8u"
    frontend-url = "https://google.com"
}

token-config {
    token-duration = 600000
}