CREATE TABLE jobs (
    id UUID PRIMARY KEY,
    date BIGINT,
    ownerEmail TEXT,
    active BOOLEAN,
    company TEXT,
    title TEXT,
    description TEXT,
    externalUrl TEXT,
    remote BOOLEAN,
    location TEXT,
    salaryLo INTEGER,
    salaryHi INTEGER,
    currency TEXT,
    country TEXT,
    tags TEXT[],
    image TEXT,
    seniority TEXT,
    other TEXT
);

INSERT INTO jobs (
    id,
    date,
    ownerEmail,
    active,
    company,
    title,
    description,
    externalUrl,
    remote,
    location,
    salaryLo,
    salaryHi,
    currency,
    country,
    tags,
    image,
    seniority,
    other
) VALUES (
    '843df718-ec6e-4d49-9289-f799c0f40064',
    1659186086,
    'daniel@rockthejvm.com',
    false,
    'Awesome Company',
    'Tech Lead',
    'An awesome job in Berlin',
    'https://rockthejvm.com/awesomejob',
    false,
    'Berlin',
    2000,
    3000,
    'EUR',
    'Germany',
    ARRAY [ 'scala', 'scala-3', 'cats' ],
    NULL,
    'Senior',
    NULL
);